### ISSUE TITLE
More coutries

### ISSUE THREAD

**Issue by xOscarDelta** [teddy-vltn/vinted-monitor#2]
Do you know of any way to change the monitor to pull from other vinted websites (UK)?

**Comment by teddy-vltn** [comment]
It can pull from other country 
```javascript
  const vintedMonitor = new VintedMonitor('https://www.vinted.uk');
  vintedMonitor.useSelenium(true);
```

Using selenium is required for now, i will try to fix the API for other other country in this week. It is the only setup that works for now. 

And the `vinted.configure` can be quite acting weird for now as well (i need to scrape other country dataset) use something along the way for the best result for now, use only those parameters: (you can put whatever you want inside tho, brands dataset should work on all vinted domains)

```javascript
  await vintedMonitor.configure({
      search_text: 'Sweatshirt M',
      order: 'newest_first',  // Ensures that the monitor fetches the newest items available.
      brands: ['Nike', 'Adidas'],  // Specify brands to monitor.
      priceFrom: 10,  // Set minimum price filter.
      priceTo: 100  // Set maximum price filter.
  });
```

I need to setup some servers to scrape other country dataset it might takes some time before this get upgraded.

**Comment by teddy-vltn** [comment]
The two last commits have fixed the API not working for different country. You can now choose between API or Selenium.

**Comment by teddy-vltn** [comment]
8d958f2

**Comment by teddy-vltn** [comment]
@xOscarDelta 32fab01 All countries have been added normally especially www.vinted.co.uk, it should work don't forget to clone again and modify the .env to your liking to configure.
