### ISSUE TITLE
Telegram bot stops sending notification after the first 5 items

### ISSUE THREAD

**Issue by orzynico** [teddy-vltn/vinted-monitor#5]
Telegram bot stops sending notification after the first 5 items. From the console Log it seems searching items but the bot doesn't receive the items.

**Comment by teddy-vltn** [comment]
@orzynico It should still send and receive new items in theory. Can you provide me your `telegram.js` file. I can assist you better on https://discord.gg/WatbRXcj if you need assistance making it work.

**Comment by orzynico** [comment]
I've just writed on the channel. Thank youuuu
